### ISSUE TITLE
About your project

### ISSUE THREAD

**Issue by sourcedexter** [Chirarg007/CryptographywithTCP-IP#1]
Hello,
Is looks amazing, I just have one suggestion,
Please make your README more readable  i.e by formatting the instructions a little bit. 

Also, there is a very well known protocol called "scp"(secure copy) , you might be interested in that ,as  that too does a similar work, but has a few drawbacks.

**Comment by ChiragVaghela10** [comment]
Hi,
Oops, I've updated the readme you can check it now.

And may be but my main concern was just to IMPLEMENT RSA algorithm and that is the reason I took help from your program for client-server thing.

**Comment by sourcedexter** [comment]
oh alright.
